-- Auto-generated by import_variants_and_images.py
-- Upsert product variants with prices and images from produits_variantes_prix.xlsx

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Liqui Moly: Huile de boîte de vitesses à double embrayage 8100
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Huile de boîte de vitesses à double%')
     OR LOWER(slug) LIKE LOWER('%huile-de-boite-de-vitesses-a-d%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 60.0, 10, 'VAR-LIQU-HUILEDEB-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 60.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-huile-de-boite-de-vitesses-a-double-embrayage-810.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 2. Liqui Moly: Leichtlauf High Tech 5W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Leichtlauf High Tech 5W-40%')
     OR LOWER(slug) LIKE LOWER('%leichtlauf-high-tech-5w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 35.0, 10, 'VAR-LIQU-LEICHTLA-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 35.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '4L', 125.0, 10, 'VAR-LIQU-LEICHTLA-4L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 125.0, volume = '4L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 155.0, 10, 'VAR-LIQU-LEICHTLA-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 155.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-leichtlauf-high-tech-5w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 3. Liqui Moly: Molygen New Generation 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Molygen New Generation 10W-40%')
     OR LOWER(slug) LIKE LOWER('%molygen-new-generation-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 40.0, 10, 'VAR-LIQU-MOLYGENN-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 40.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 160.0, 10, 'VAR-LIQU-MOLYGENN-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 160.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-molygen-new-generation-10w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 4. Liqui Moly: Molygen New Generation 5W-30
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Molygen New Generation 5W-30%')
     OR LOWER(slug) LIKE LOWER('%molygen-new-generation-5w-30%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 42.0, 10, 'VAR-LIQU-MOLYGENN-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 42.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 170.0, 10, 'VAR-LIQU-MOLYGENN-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 170.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-molygen-new-generation-5w-30.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 5. Liqui Moly: Molygen New Generation 5W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Molygen New Generation 5W-40%')
     OR LOWER(slug) LIKE LOWER('%molygen-new-generation-5w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 45.0, 10, 'VAR-LIQU-MOLYGENN-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 45.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 185.0, 10, 'VAR-LIQU-MOLYGENN-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 185.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-molygen-new-generation-5w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 6. Liqui Moly: MoS2 Leichtlauf 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%MoS2 Leichtlauf 10W-40%')
     OR LOWER(slug) LIKE LOWER('%mos2-leichtlauf-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 35.0, 10, 'VAR-LIQU-MOS2LEIC-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 35.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '4L', 102.5, 10, 'VAR-LIQU-MOS2LEIC-4L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 102.5, volume = '4L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 125.0, 10, 'VAR-LIQU-MOS2LEIC-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 125.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-mos2-leichtlauf-10w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 7. Liqui Moly: Special Tec AA 5W-20
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Special Tec AA 5W-20%')
     OR LOWER(slug) LIKE LOWER('%special-tec-aa-5w-20%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 42.0, 10, 'VAR-LIQU-SPECIALT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 42.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 174.0, 10, 'VAR-LIQU-SPECIALT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 174.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-special-tec-aa-5w-20.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 8. Liqui Moly: Special Tec F 0W-30
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Special Tec F 0W-30%')
     OR LOWER(slug) LIKE LOWER('%special-tec-f-0w-30%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 57.0, 10, 'VAR-LIQU-SPECIALT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 57.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 230.0, 10, 'VAR-LIQU-SPECIALT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 230.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-special-tec-f-0w-30.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 9. Liqui Moly: Special Tec F 5W-30 (FORD)
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Special Tec F 5W-30 (FORD)%')
     OR LOWER(slug) LIKE LOWER('%special-tec-f-5w-30-ford%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 45.0, 10, 'VAR-LIQU-SPECIALT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 45.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 154.0, 10, 'VAR-LIQU-SPECIALT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 154.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-special-tec-f-5w-30-ford.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 10. Liqui Moly: Special Tec F ECO 5W-20
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Special Tec F ECO 5W-20%')
     OR LOWER(slug) LIKE LOWER('%special-tec-f-eco-5w-20%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 40.0, 10, 'VAR-LIQU-SPECIALT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 40.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 175.0, 10, 'VAR-LIQU-SPECIALT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 175.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-special-tec-f-eco-5w-20.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 11. Liqui Moly: Super Leichtlauf 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Super Leichtlauf 10W-40%')
     OR LOWER(slug) LIKE LOWER('%super-leichtlauf-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 28.0, 10, 'VAR-LIQU-SUPERLEI-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 28.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '4L', 89.5, 10, 'VAR-LIQU-SUPERLEI-4L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 89.5, volume = '4L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 110.0, 10, 'VAR-LIQU-SUPERLEI-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 110.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-super-leichtlauf-10w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 12. Liqui Moly: Synthoil Race Tech GT1 10W-60
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Synthoil Race Tech GT1 10W-60%')
     OR LOWER(slug) LIKE LOWER('%synthoil-race-tech-gt1-10w-60%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 55.0, 10, 'VAR-LIQU-SYNTHOIL-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 55.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 200.0, 10, 'VAR-LIQU-SYNTHOIL-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 200.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-synthoil-race-tech-gt1-10w-60.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 13. Liqui Moly: Top Tec 4100 5W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 4100 5W-40%')
     OR LOWER(slug) LIKE LOWER('%top-tec-4100-5w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 37.0, 10, 'VAR-LIQU-TOPTEC41-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 37.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 157.0, 10, 'VAR-LIQU-TOPTEC41-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 157.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-4100-5w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 14. Liqui Moly: Top Tec 4110 5W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 4110 5W-40%')
     OR LOWER(slug) LIKE LOWER('%top-tec-4110-5w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 36.0, 10, 'VAR-LIQU-TOPTEC41-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 36.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 154.0, 10, 'VAR-LIQU-TOPTEC41-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 154.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-4110-5w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 15. Liqui Moly: Top Tec 4200 5W-30 New Generation
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 4200 5W-30 New Generation%')
     OR LOWER(slug) LIKE LOWER('%top-tec-4200-5w-30-new-generat%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 46.0, 10, 'VAR-LIQU-TOPTEC42-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 46.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 190.0, 10, 'VAR-LIQU-TOPTEC42-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 190.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-4200-5w-30-new-generation.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 16. Liqui Moly: Top Tec 4300 5W-30 (PSA)
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 4300 5W-30 (PSA)%')
     OR LOWER(slug) LIKE LOWER('%top-tec-4300-5w-30-psa%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 43.0, 10, 'VAR-LIQU-TOPTEC43-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 43.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 160.0, 10, 'VAR-LIQU-TOPTEC43-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 160.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-4300-5w-30-psa.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 17. Liqui Moly: Top Tec 4600 5W-30
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 4600 5W-30%')
     OR LOWER(slug) LIKE LOWER('%top-tec-4600-5w-30%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 40.0, 10, 'VAR-LIQU-TOPTEC46-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 40.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 170.0, 10, 'VAR-LIQU-TOPTEC46-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 170.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-4600-5w-30.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 18. Liqui Moly: Top Tec 6100 0W-30
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 6100 0W-30%')
     OR LOWER(slug) LIKE LOWER('%top-tec-6100-0w-30%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 46.0, 10, 'VAR-LIQU-TOPTEC61-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 46.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 174.0, 10, 'VAR-LIQU-TOPTEC61-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 174.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-6100-0w-30.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 19. Liqui Moly: Top Tec 6200 0W-20
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec 6200 0W-20%')
     OR LOWER(slug) LIKE LOWER('%top-tec-6200-0w-20%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 60.0, 10, 'VAR-LIQU-TOPTEC62-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 60.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 260.0, 10, 'VAR-LIQU-TOPTEC62-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 260.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-6200-0w-20.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 20. Liqui Moly: Top Tec ATF 1100
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec ATF 1100%')
     OR LOWER(slug) LIKE LOWER('%top-tec-atf-1100%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 40.0, 10, 'VAR-LIQU-TOPTECAT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 40.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 160.0, 10, 'VAR-LIQU-TOPTECAT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 160.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-atf-1100.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 21. Liqui Moly: Top Tec ATF 1200
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec ATF 1200%')
     OR LOWER(slug) LIKE LOWER('%top-tec-atf-1200%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 50.0, 10, 'VAR-LIQU-TOPTECAT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 50.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 210.0, 10, 'VAR-LIQU-TOPTECAT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 210.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-atf-1200.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 22. Liqui Moly: Top Tec ATF 1800
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Top Tec ATF 1800%')
     OR LOWER(slug) LIKE LOWER('%top-tec-atf-1800%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 60.0, 10, 'VAR-LIQU-TOPTECAT-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 60.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 270.0, 10, 'VAR-LIQU-TOPTECAT-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 270.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/liqui-moly-top-tec-atf-1800.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 23. Mannol: Classic 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Classic 10W-40%')
     OR LOWER(slug) LIKE LOWER('%classic-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 21.0, 10, 'VAR-MANN-CLASSIC1-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 21.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 67.0, 10, 'VAR-MANN-CLASSIC1-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 67.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '7L', 90.0, 10, 'VAR-MANN-CLASSIC1-7L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 90.0, volume = '7L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/mannol-classic-10w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 24. Mannol: Defender 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Defender 10W-40%')
     OR LOWER(slug) LIKE LOWER('%defender-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '4L', 100.0, 10, 'VAR-MANN-DEFENDER-4L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 100.0, volume = '4L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 135.0, 10, 'VAR-MANN-DEFENDER-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 135.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/mannol-defender-10w-40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 25. Mannol: Diesel Extra 10W-40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Diesel Extra 10W-40%')
     OR LOWER(slug) LIKE LOWER('%diesel-extra-10w-40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 23.0, 10, 'VAR-MANN-DIESELEX-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 23.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 90.0, 10, 'VAR-MANN-DIESELEX-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 90.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
  END IF;
END $$;

-- 26. Mannol: Energy Combi LL 5W-30
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Energy Combi LL 5W-30%')
     OR LOWER(slug) LIKE LOWER('%energy-combi-ll-5w-30%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 40.0, 10, 'VAR-MANN-ENERGYCO-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 40.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 170.0, 10, 'VAR-MANN-ENERGYCO-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 170.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/mannol-energy-combi-ll-5w-30.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 27. Wolf: Guardtech 10W40 B4
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Guardtech 10W40 B4%')
     OR LOWER(slug) LIKE LOWER('%guardtech-10w40-b4%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 20.0, 10, 'VAR-WOLF-GUARDTEC-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 20.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 89.0, 10, 'VAR-WOLF-GUARDTEC-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 89.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/wolf-guardtech-10w40-b4.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 28. Wolf: Officialtech 5W30 C3 SP Extra
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Officialtech 5W30 C3 SP Extra%')
     OR LOWER(slug) LIKE LOWER('%officialtech-5w30-c3-sp-extra%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 29.0, 10, 'VAR-WOLF-OFFICIAL-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 29.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 125.0, 10, 'VAR-WOLF-OFFICIAL-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 125.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/wolf-officialtech-5w30-c3-sp-extra.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 29. Wolf: Officialtech 5W30 MS-Ford
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Officialtech 5W30 MS-Ford%')
     OR LOWER(slug) LIKE LOWER('%officialtech-5w30-ms-ford%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 31.0, 10, 'VAR-WOLF-OFFICIAL-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 31.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 131.0, 10, 'VAR-WOLF-OFFICIAL-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 131.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/wolf-officialtech-5w30-ms-ford.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- 30. Wolf: Vitaltech 5W40
DO $$
DECLARE prod_id text; BEGIN
  SELECT id INTO prod_id FROM public."Product"
  WHERE LOWER("nameFr") LIKE LOWER('%Vitaltech 5W40%')
     OR LOWER(slug) LIKE LOWER('%vitaltech-5w40%')
  LIMIT 1;
  IF prod_id IS NOT NULL THEN
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '1L', 26.0, 10, 'VAR-WOLF-VITALTEC-1L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 26.0, volume = '1L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductVariant" (id, "productId", volume, price, "stockQty", "skuVariant")
    VALUES (gen_random_uuid()::text, prod_id, '5L', 108.0, 10, 'VAR-WOLF-VITALTEC-5L')
    ON CONFLICT ("skuVariant") DO UPDATE SET price = 108.0, volume = '5L', "stockQty" = GREATEST("ProductVariant"."stockQty", 5);
    INSERT INTO public."ProductImage" (id, "productId", url, "isPrimary", "sortOrder")
    VALUES (gen_random_uuid()::text, prod_id, '/uploads/products/wolf-vitaltech-5w40.jpg', true, 0)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

COMMIT;