-- Add detailed vehicle fields to UserCar and remove plate number
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "vin" TEXT;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "engine" TEXT;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "displacement" DOUBLE PRECISION;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "cylinders" INTEGER;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "fuel" TEXT;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "power" DOUBLE PRECISION;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "transmission" TEXT;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "trim" TEXT;
ALTER TABLE "UserCar" ADD COLUMN IF NOT EXISTS "productionDate" TEXT;
ALTER TABLE "UserCar" DROP COLUMN IF EXISTS "plateNumber";